// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/catalog/p/:productSlug": {
    params: {
      "productSlug": string;
    };
  };
  "/catalog/c/:categorySlug?": {
    params: {
      "categorySlug"?: string;
    };
  };
  "/catalog/files/*": {
    params: {
      "*": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/cart/add": {
    params: {};
  };
  "/cart/checkout": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/catalog" | "/catalog/p/:productSlug" | "/catalog/c/:categorySlug?" | "/catalog/files/*" | "/cart" | "/cart/add" | "/cart/checkout" | "/account" | "/account/orders" | "/account/profile" | "/auth/register" | "/auth/login" | "/auth/logout" | "/*";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/catalog/index.tsx": {
    id: "routes/catalog/index";
    page: "/catalog";
  };
  "./routes/catalog/product.tsx": {
    id: "routes/catalog/product";
    page: "/catalog/p/:productSlug";
  };
  "./routes/catalog/category.tsx": {
    id: "routes/catalog/category";
    page: "/catalog/c/:categorySlug?";
  };
  "./routes/catalog/files.tsx": {
    id: "routes/catalog/files";
    page: "/catalog/files/*";
  };
  "./routes/cart/index.tsx": {
    id: "routes/cart/index";
    page: "/cart";
  };
  "./routes/cart/add.tsx": {
    id: "routes/cart/add";
    page: "/cart/add";
  };
  "./routes/cart/checkout.tsx": {
    id: "routes/cart/checkout";
    page: "/cart/checkout";
  };
  "./routes/account/_layout.tsx": {
    id: "routes/account/_layout";
    page: "/account" | "/account/orders" | "/account/profile";
  };
  "./routes/account/index.tsx": {
    id: "routes/account/index";
    page: "/account";
  };
  "./routes/account/orders.tsx": {
    id: "routes/account/orders";
    page: "/account/orders";
  };
  "./routes/account/profile.tsx": {
    id: "routes/account/profile";
    page: "/account/profile";
  };
  "./routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/auth/register";
  };
  "./routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "./routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/auth/logout";
  };
  "./routes/catchall.tsx": {
    id: "routes/catchall";
    page: "/*";
  };
};